### PR TITLE
Update to 1.19.x

### PR DESCRIPTION
**Pull request by MegaTophat**
Update to all sub-versions of 1.19 while dropping support for 1.18.x entirely. Note that 1.19 itself is not supported, as chat signing changed the way commands are handled within the client in 1.19.1.

I would recommend squashing the commits from this repository as I made many commits to make auditing this PR as painless as possible.

### CODE REVIEW

**Comment by MegaTophat** [comment]
If 1.18.x support is still to be desired within the same jar, I can work on using abstraction to make that possible. For now though, creating a separate jar is the easiest way to update.

**Comment by MegaTophat** [comment]
Also if this PR is merged don't forget to attach this to the currently open "Update" issue and mark the issue as resolved.

**Comment by MegaTophat** [comment]
@fxmorin Don't forget to create a new release so people don't have to compile from source for 1.19.x if they don't know how to.

**Comment by FxMorin** [comment]
@MegaTophat I'm too busy to update this at the moment. However like before I don't mind merging in your changes.
Honestly if you want I can give you collaborator on this project.

Btw you can use the fabric API if you want. Would make the client commands a heck of a lot easier to manage

**Pull request merged**
